name: check yanny

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: testing
          env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_KEY: "foo"
          run: ls && ./checkyanny.sh && echo "$AWS_ACCESS_KEY_ID" && echo "$AWS_SECRET_KEY"
